modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tp"
version = "${version}"
displayName = "TintedPotions"
authors = "Qzimyion"
description = '''
Assigns the potions in a brewing stand a different colour depending on the potion in the slot.
'''
#logoFile = ""

[[dependencies.tp]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tp]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tp]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tp.mixins.json"
